# Generated by Django 4.2.4 on 2023-08-14 21:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Brand Name')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Country Name')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Country Code')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Model')),
                ('price', models.PositiveIntegerField(verbose_name='Price')),
                ('color', models.CharField(max_length=50, verbose_name='Color')),
                ('size', models.FloatField(validators=[django.core.validators.MinValueValidator(0, message='Value must be greater than or equal to 0.')], verbose_name='Display size')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.brand', to_field='name', verbose_name='Brand')),
                ('built', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.country', to_field='name', verbose_name='Made IN')),
            ],
            options={
                'verbose_name': 'Phone',
                'verbose_name_plural': 'Mobile Phones',
            },
        ),
        migrations.AddField(
            model_name='brand',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.country', verbose_name='Nationality'),
        ),
    ]
