# Generated by Django 4.2.4 on 2023-08-08 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_country_code_alter_country_name_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.country', to_field='code', verbose_name='Nationality'),
        ),
    ]
