# Generated by Django 4.2.4 on 2023-08-08 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_brand_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.country', verbose_name='Nationality'),
        ),
    ]
