# Generated by Django 4.2.4 on 2023-08-08 09:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_brand_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Model')),
                ('price', models.PositiveIntegerField(verbose_name='Price')),
                ('color', models.CharField(max_length=50, verbose_name='Color')),
                ('size', models.FloatField(validators=[django.core.validators.MinValueValidator(0, message='Value must be greater than or equal to 0.')], verbose_name='Display size')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.brand', verbose_name='Brand')),
                ('built', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.country', verbose_name='Made IN')),
            ],
            options={
                'verbose_name': 'Phone',
                'verbose_name_plural': 'Mobile Phones',
            },
        ),
    ]
